<a href="https://colab.research.google.com/github/LeoMcBills/ML-Algo-Exploration/blob/main/tfbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Tensorflow basics

- Casting
- Initialization
- Indexing
- Broadcasting
- Algebraic Operations
- Matrix Operations
- Commonly used functions in machine learning
- Ragged tensors
- Sparse tensors
- String tensors

The above is what is going to be demonstrated in this notebook

# What are tensors?
- Tensors are multi-dimensional arrays

# What is an Array?
- An array is an ordered arrangement of numbers

# Introduction to <b>Initializing and casting</b> of tensors  
## Dimensions of tensors  
- Zero dimension e.g 8
- One dimension e.g [4, 3, 2]
- two dimension e.g [[5, 3, 5], [4, 2, 6], [3, 2, 7]]
- three dimension e.g [[[4, 2, 5], [2, 3, 4]], [[6, 3, 2], [9, 0, 3]]]

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
zeroDtensor = tf.constant(8)
print(zeroDtensor)
print("This is the shape of a zero dimensional tensor:",zeroDtensor.shape)

print()

oneDtensor = tf.constant([4, 3, 2])
print(oneDtensor)
print("This is the shape of a one dimensional tensor:", oneDtensor.shape)

print()

twoDtensor = tf.constant([[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7],
                          ])
print(twoDtensor)
print("This the shape of a two dimensional tensor:", twoDtensor.shape)

print()

threeDtensor = tf.constant([[[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7]],
                          [[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7]]
                          ])
print(threeDtensor)
print("This is the shape of a three dimensional tensor:", threeDtensor.shape)

tf.Tensor(8, shape=(), dtype=int32)
This is the shape of a zero dimensional tensor: ()

tf.Tensor([4 3 2], shape=(3,), dtype=int32)
This is the shape of a one dimensional tensor: (3,)

tf.Tensor(
[[5 3 5]
 [4 2 6]
 [3 2 7]], shape=(3, 3), dtype=int32)
This the shape of a two dimensional tensor: (3, 3)

tf.Tensor(
[[[5 3 5]
  [4 2 6]
  [3 2 7]]

 [[5 3 5]
  [4 2 6]
  [3 2 7]]], shape=(2, 3, 3), dtype=int32)
This is the shape of a three dimensional tensor: (2, 3, 3)


In [4]:
# the following returns the number of dimensions of a given tensor
print("This is a", zeroDtensor.ndim, "dimensional tensor.")
print("This is a", oneDtensor.ndim, "dimensional tensor.")
print("This is a", twoDtensor.ndim, "dimensional tensor.")
print("This is a", threeDtensor.ndim, "dimensional tensor.")

This is a 0 dimensional tensor.
This is a 1 dimensional tensor.
This is a 2 dimensional tensor.
This is a 3 dimensional tensor.


# CASTING TENSORS  
Imagine you want to convert a tensor with a datatype of float32 to int32 or int16, let me use the dtype=int32 in the tf.constant function you talk to yourself. Well to break to you the bad news, an error reading "Cannot convert [2, 5.0, 3, 2, 4] to EagerTensor of dtype int32" just like shown below.  
Don't give up on doing so though, because the tf.cast method comes handy for this as it allows for the conversion of floating point tensors into integer type tensor.   
## So let's do this practically

In [6]:
oneDtensor = tf.constant([2, 5., 3, 2, 4], dtype=tf.int32)

TypeError: ignored

In [7]:
oneDtensor = tf.constant([2, 5., 3, 2, 4], dtype=tf.float32)

In [8]:
print(oneDtensor)

tf.Tensor([2. 5. 3. 2. 4.], shape=(5,), dtype=float32)


## Let's cast our tensor now

In [10]:
castOneDtensor = tf.cast(oneDtensor, dtype=tf.int16)

In [12]:
print(castOneDtensor)

# Congs, our quest is successfully completed

tf.Tensor([2 5 3 2 4], shape=(5,), dtype=int16)


# Other tensorflow methods

In [15]:
# Conversion of a numpy array into a tensor
np_array = np.array([1, 2, 3])
Converted_tensor = tf.convert_to_tensor(np_array)
print(Converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [18]:
# let's construct an identity matrix or a batch of matrices
eye_tensor = tf.eye(num_rows=3)
print(eye_tensor)
print(eye_tensor*3)

eye_tensor1 = tf.eye(3,
                     batch_shape=[5,],
                     dtype=tf.dtypes.float32,
                     )
print(eye_tensor1)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(5, 3, 3), dtype=float32)


# <b>Assignment</b>
## Look at the following in the tensorflow documentation  
- fill method  
- ones method
- ones_like method
- zeros method
- shape method
- rank method
- tf.random.normal
- tf.random.uniform
- seed method

### Please check this link out too
[acsu.buffalo.edu/-adamcunn/probability/normal.html](https://acsu.buffalo.edu/-adamcunn/probability/normal.html)

# INDEXING

In [22]:
tensor_indexed = tf.constant([3, 2, 4, 1, 4, 6])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[...])

tensor_two_d = tf.constant([[1, 2, 3],
                            [2, 3, 1],
                            [9, 4, 2],
                            [3, 3, 1],
                            ])
print(tensor_two_d[ 0:2, 0:1])
print(tensor_two_d[ ..., 0:1])
print(tensor_two_d[ 0:2, ...])

tf.Tensor([3 2 4 1 4 6], shape=(6,), dtype=int32)
tf.Tensor([3 2 4 1], shape=(4,), dtype=int32)
tf.Tensor([3 2 4 1 4 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [9]
 [3]], shape=(4, 1), dtype=int32)
tf.Tensor(
[[1 2 3]
 [2 3 1]], shape=(2, 3), dtype=int32)


# MATH OPERATIONS

In [23]:
# abs
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [24]:
# addition
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype=tf.int32)
x_2 = tf.constant([7, 6, 2, 6, 7, 11], dtype=tf.int32)
print(tf.add(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


# Broadcasting in tensorflow

In [26]:
x_3 = tf.constant([7], dtype=tf.int32)
print(tf.math.add(x_1, x_3))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [28]:
x_argmax = tf.constant([200, 120, 130, 300, 3])
print(tf.math.argmax(x_argmax))
# the above function is to get index of the the maximum value of the tensor

tf.Tensor(3, shape=(), dtype=int64)


In [30]:
x = tf.constant([[2, 2],
                 [3, 3]])

y = tf.constant([[3, 0],
                 [1, 4]])

print(tf.pow(x, y))

tf.Tensor(
[[ 8  1]
 [ 3 81]], shape=(2, 2), dtype=int32)


### Reduce method

In [31]:
tensor_two_d = tf.constant([[1, -2, 3],
                            [3, 2, 2],
                            [1, 1, 1],
                            [7, 3, 2],
                            ])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d, axis=1, keepdims=False, name=None))
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None))

(4, 3)
tf.Tensor([ 2  7  3 12], shape=(4,), dtype=int32)
tf.Tensor([12  4  8], shape=(3,), dtype=int32)


### tf.math.sigmoid
Formula;  
sigmoid(x) => y = 1 / (1 + exp(-x))  

In [32]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

## tf.math.top_k


In [33]:
tf.math.top_k(tensor_two_d, k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 1],
       [3, 2],
       [1, 1],
       [7, 3]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 0],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int32)>)