<a href="https://colab.research.google.com/github/LeoMcBills/ML-Algo-Exploration/blob/main/tfbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Tensorflow basics

- Casting
- Initialization
- Indexing
- Broadcasting
- Algebraic Operations
- Matrix Operations
- Commonly used functions in machine learning
- Ragged tensors
- Sparse tensors
- String tensors

The above is what is going to be demonstrated in this notebook

# What are tensors?
- Tensors are multi-dimensional arrays

# What is an Array?
- An array is an ordered arrangement of numbers

# Introduction to <b>Initializing and casting</b> of tensors  
## Dimensions of tensors  
- Zero dimension e.g 8
- One dimension e.g [4, 3, 2]
- two dimension e.g [[5, 3, 5], [4, 2, 6], [3, 2, 7]]
- three dimension e.g [[[4, 2, 5], [2, 3, 4]], [[6, 3, 2], [9, 0, 3]]]

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
zeroDtensor = tf.constant(8)
print(zeroDtensor)
print("This is the shape of a zero dimensional tensor:",zeroDtensor.shape)

print()

oneDtensor = tf.constant([4, 3, 2])
print(oneDtensor)
print("This is the shape of a one dimensional tensor:", oneDtensor.shape)

print()

twoDtensor = tf.constant([[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7],
                          ])
print(twoDtensor)
print("This the shape of a two dimensional tensor:", twoDtensor.shape)

print()

threeDtensor = tf.constant([[[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7]],
                          [[5, 3, 5],
                          [4, 2, 6],
                          [3, 2, 7]]
                          ])
print(threeDtensor)
print("This is the shape of a three dimensional tensor:", threeDtensor.shape)

tf.Tensor(8, shape=(), dtype=int32)
This is the shape of a zero dimensional tensor: ()

tf.Tensor([4 3 2], shape=(3,), dtype=int32)
This is the shape of a one dimensional tensor: (3,)

tf.Tensor(
[[5 3 5]
 [4 2 6]
 [3 2 7]], shape=(3, 3), dtype=int32)
This the shape of a two dimensional tensor: (3, 3)

tf.Tensor(
[[[5 3 5]
  [4 2 6]
  [3 2 7]]

 [[5 3 5]
  [4 2 6]
  [3 2 7]]], shape=(2, 3, 3), dtype=int32)
This is the shape of a three dimensional tensor: (2, 3, 3)


In [4]:
# the following returns the number of dimensions of a given tensor
print("This is a", zeroDtensor.ndim, "dimensional tensor.")
print("This is a", oneDtensor.ndim, "dimensional tensor.")
print("This is a", twoDtensor.ndim, "dimensional tensor.")
print("This is a", threeDtensor.ndim, "dimensional tensor.")

This is a 0 dimensional tensor.
This is a 1 dimensional tensor.
This is a 2 dimensional tensor.
This is a 3 dimensional tensor.


# CASTING TENSORS  
Imagine you want to convert a tensor with a datatype of float32 to int32 or int16, let me use the dtype=int32 in the tf.constant function you talk to yourself. Well to break to you the bad news, an error reading "Cannot convert [2, 5.0, 3, 2, 4] to EagerTensor of dtype int32" just like shown below.  
Don't give up on doing so though, because the tf.cast method comes handy for this as it allows for the conversion of floating point tensors into integer type tensor.   
## So let's do this practically

In [6]:
oneDtensor = tf.constant([2, 5., 3, 2, 4], dtype=tf.int32)

TypeError: ignored

In [7]:
oneDtensor = tf.constant([2, 5., 3, 2, 4], dtype=tf.float32)

In [8]:
print(oneDtensor)

tf.Tensor([2. 5. 3. 2. 4.], shape=(5,), dtype=float32)


## Let's cast our tensor now

In [10]:
castOneDtensor = tf.cast(oneDtensor, dtype=tf.int16)

In [12]:
print(castOneDtensor)

# Congs, our quest is successfully completed

tf.Tensor([2 5 3 2 4], shape=(5,), dtype=int16)
